export const BASE_URL = 'http://ehisaab.app/ehisaab/api'
export const IMAGE_URL = 'http://ehisaab.app/ehisaab/'
export const GET_STORE = '/store/get.php' 
export const GET_CATEGORY = '/businessCategories/get.php'
export const GET_STORE_DETAIL = '/store/get_store_detail.php'
// export const GET_BUSINESS_LOG = ''